apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: meteor-operator-meteor-editor-role
rules:
- apiGroups:
  - meteor.zone
  resources:
  - meteors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meteor.zone
  resources:
  - meteors/status
  verbs:
  - get
