
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-meteor-operate-first-cloud-v1alpha1-meteor
  failurePolicy: Fail
  name: mmeteor.kb.io
  rules:
  - apiGroups:
    - meteor.operate-first.cloud
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - meteors
  sideEffects: None
