---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jupyterhub
  labels:
    app: meteor-pipeline
spec:
  params:
    - name: url
      type: string
    - name: ref
      type: string
    - name: uid
      type: string
  resources:
    - name: git-repo
      type: git

  tasks:
    - name: config
      taskRef:
        name: config
      params:
        - name: image
          value: $(context.pipelineRun.name)
      resources:
        inputs:
          - name: repo
            resource: git-repo

    - name: notebook-build-run
      taskRef:
        name: notebook-build
      conditions:
        - conditionRef: build-check
          resources:
            - name: repo
              resource: git-repo
      params:
        - name: url
          value: $(params.url)
        - name: image
          value: $(context.pipelineRun.name)
        - name: base_image
          value: $(tasks.config.results.base-image)
        - name: build_stratergy
          value: $(tasks.config.results.build-stratergy)
        - name: dockerfile_path
          value: $(tasks.config.results.dockerfile-path)
        - name: build_source_script
          value: $(tasks.config.results.build-source-script)
        - name: registry
          value: $(tasks.config.results.registry)
        - name: registry_org
          value: $(tasks.config.results.registry-org)
        - name: registry_project
          value: $(tasks.config.results.registry-project)
        - name: registry_secret
          value: $(tasks.config.results.registry-secret)
      resources:
        inputs:
          - name: repo
            resource: git-repo
