---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jupyterbook
  labels:
    app: meteor-pipeline
spec:
  params:
    - name: url
      type: string
    - name: ref
      type: string
    - name: uid
      type: string
  resources:
    - name: git-repo
      type: git

  tasks:
    - name: jupyterbook-build-run
      taskRef:
        name: jupyterbook-build
      params:
        - name: uid
          value: $(params.uid)
        - name: image
          value: $(context.pipelineRun.name)
      resources:
        inputs:
          - name: repo
            resource: git-repo
