# permissions for end users to edit comas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coma-editor-role
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - comas
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - comas/status
    verbs:
      - get
