# permissions for end users to view comas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coma-viewer-role
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - comas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - comas/status
    verbs:
      - get
