# permissions for end users to view meteors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meteor-viewer-role
rules:
- apiGroups:
  - meteor.operate-first.cloud
  resources:
  - meteors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meteor.operate-first.cloud
  resources:
  - meteors/status
  verbs:
  - get
