# permissions for end users to view meteorcomas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meteorcoma-viewer-role
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - meteorcomas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - meteorcomas/status
    verbs:
      - get
