# permissions for end users to view meteors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meteor-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - meteor.zone
    resources:
      - meteors
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - meteor.zone
    resources:
      - meteors/status
    verbs:
      - get
