
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - meteor.operate-first.cloud
  resources:
  - meteors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meteor.operate-first.cloud
  resources:
  - meteors/finalizers
  verbs:
  - update
- apiGroups:
  - meteor.operate-first.cloud
  resources:
  - meteors/status
  verbs:
  - get
  - patch
  - update
