# permissions for end users to view showers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shower-viewer-role
rules:
- apiGroups:
  - meteor.zone
  resources:
  - showers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meteor.zone
  resources:
  - showers/status
  verbs:
  - get
