apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: metrics-start
spec:
  params:
    - name: pipeline
    - name: pipelineRun
  steps:
    - name: metrics-start
      image: quay.io/thoth-station/s2i-thoth-dev:latest
      env:
        - name: PIPELINE_NAME
          value: $(params.pipeline)
        - name: PIPELINERUN_NAME
          value: $(params.pipelineRun)
      script: |
        #!/opt/app-root/bin/python
        import os
        from prometheus_client import CollectorRegistry, Counter, Gauge, push_to_gateway

        PROMETHEUS_REGISTRY = CollectorRegistry()

        LABEL_KEYS = ["pipeline", "pipelinerun"]
        LABEL_VALUES = [os.getenv('PIPELINE_NAME'), os.getenv('PIPELINERUN_NAME')]

        BUILD_SUBMITTED = Counter(
            "meteor_image_build_submitted",
            "Meteor image submitted for build.",
            LABEL_KEYS,
            registry=PROMETHEUS_REGISTRY,
        )
        BUILD_SUBMITTED.labels(*LABEL_VALUES).inc()

        try:
            print("Submitting metrics to Prometheus pushgateway")
            push_to_gateway(
                f"http://pushgateway:9091",
                job=os.getenv('PIPELINERUN_NAME'),
                registry=PROMETHEUS_REGISTRY,
            )
        except Exception as e:
            print(f"An error occurred pushing the metrics: {str(e)}")
